name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Check git workspace isn't dirty
        run: git diff --exit-code --quiet

      - run: bun run build
      - run: bun run typecheck
      - run: bun run test
      - run: bun --cwd apps/node-compat-test test
